### PR TITLE
add japanese translation

### PR DESCRIPTION
**Pull request by mitsuami-megane**
It builds but displays all �'s in the client. I think the font is missing the glyphs.

### CODE REVIEW

**Comment by xytovl** [comment]
Thanks for the translations, there's some work in progress in https://github.com/Meumeu/WiVRn/tree/i18n to use a correct font and not require to manually set the glyph range.

**Comment by mitsuami-megane** [comment]
i added my .po on top of i18n branch, but i'm just getting regular question marks now, not even �'s

**Comment by Meumeu** [comment]
i18n branch should be working now, I've included your commit as well

**Comment by mitsuami-megane** [comment]
confirmed, works great!

**Pull request closed without merging**
