### PR TITLE
OpenXR standard loader (instead of oculus)

### PR DESCRIPTION
**Pull request by technobaboo**
Not quite done yet, having bugs... figured I'd put the code here and we could work together to get it working!

All the latest oculus versions support the standard loader, as does Lynx, ML2, etc. so I figured why not just use that instead? version 1.0.28 just released! This would cut down the number of APKs to 2 per architecture until pico adopts the standard loader! then we'd just need an x86_64 one for ML2 and arm64 for vive flow, lynx, quest, pico, google cardboard (since monado on phones), etc.

### CODE REVIEW

**Comment by xytovl** [comment]
That's great, I'll need to check if Quest 1 works with standard loader.

Which hardware will you be able to test with?

**Comment by technobaboo** [comment]
currently it has an error preventing it from building, but I can test with the magic leap 2 and quest 2 while i'm staying in SF for about a week!

**Comment by xytovl** [comment]
I am checking what breaks the build, and have pushed a commit on https://github.com/Meumeu/WiVRn/tree/standard-openxr-loader, I think I should be able to push to your branch directly, would you prefer that?

We had a name collision in CMakeLists.txt
Now there is a problem with vulkan handles, they get defined to integers instead of opaque pointers, and C++ function overloading over handle type doesn't work.

**Comment by technobaboo** [comment]
I'm ok with you pushing to wherever as long as I can push to there too! I invited you to my fork but if you can add me to wivrn's I'd be happy to help

**Comment by xytovl** [comment]
It now works on Quest 1, if you can confirm for Quest 2 that is sufficient to integrate. If it also works for Magic Leap 2 then it's perfect.

**Comment by technobaboo** [comment]
we can't restrict the architecture then, magic leap 2 is x86_64... will try that

**Comment by xytovl** [comment]
The actual issue is that we have a constructor overloaded with `VkImage` and `VkBuffer`, and on architectures where pointers are 32 bits, they are the same type. There should be no problem with x86_64.

**Comment by technobaboo** [comment]
cool! how do i add that architecture to the abi filter?

**Comment by xytovl** [comment]
> cool! how do i add that architecture to the abi filter?

Done in https://github.com/Meumeu/WiVRn/pull/9/commits/42a30c947537bdabcbc0222baa4a36c99350eb46: `abiFilters 'arm64-v8a', 'x86_64'`

You just need to test the apk from https://github.com/Meumeu/WiVRn/actions/runs/5546349535?pr=9#artifacts

**Comment by technobaboo** [comment]
```
7-13 19:41:02.741  3969  3969 D StatusBar: package name = org.meumeu.wivrn
07-13 19:42:22.931  5737  5737 E MLPackageVerifier::Verifier: Package org.meumeu.wivrn signature not match
07-13 19:42:22.931  5737  5737 E MLPackageVerifier::Verifier: Reject package: org.meumeu.wivrn permissive=1
07-13 19:42:22.936  3773  3801 I ActivityManager: Force stopping org.meumeu.wivrn appid=10067 user=-1: installPackageLI
07-13 19:42:22.936  3773  3817 I PackageManager: Update package org.meumeu.wivrn code path from /data/app/org.meumeu.wivrn-HxC3cbjh_Pd242yQFVHOcw== to /data/app/org.meumeu.wivrn-09rDM-Al64bXn1zf1payaw==; Retain data and using new
07-13 19:42:22.936  3773  3817 I PackageManager: Update package org.meumeu.wivrn resource path from /data/app/org.meumeu.wivrn-HxC3cbjh_Pd242yQFVHOcw== to /data/app/org.meumeu.wivrn-09rDM-Al64bXn1zf1payaw==; Retain data and using new
07-13 19:42:22.936  3773  3801 I ActivityManager: Killing 6865:org.meumeu.wivrn/u0a67 (adj 0): stop org.meumeu.wivrn
07-13 19:42:22.937  3773  3801 W ActivityTaskManager: Force removing ActivityRecord{d989e01 u0 org.meumeu.wivrn/android.app.NativeActivity t175 f}: app died, no saved state
07-13 19:42:22.989  3773  3817 I ActivityManager: Force stopping org.meumeu.wivrn appid=10067 user=0: pkg removed
07-13 19:42:22.993  3773  3801 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_REMOVED dat=package:org.meumeu.wivrn flg=0x4000010 (has extras) } to com.android.musicfx/.Compatibility$Receiver
07-13 19:42:22.995  3947  3947 D AvrcpMediaPlayerList: Name of package changed: org.meumeu.wivrn
07-13 19:42:22.995  3773  3801 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_ADDED dat=package:org.meumeu.wivrn flg=0x4000010 (has extras) } to com.android.packageinstaller/.PackageInstalledReceiver
07-13 19:42:22.995  3773  3801 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_ADDED dat=package:org.meumeu.wivrn flg=0x4000010 (has extras) } to com.android.musicfx/.Compatibility$Receiver
07-13 19:42:23.003  3464  3693 I VoiceService: offline_intent_iface.cpp:389: [updateVarVecValues2SysGramStr]----- The values of VoiceConcept 1 (string App) updated to (ar brochure)|(custom fit)|(featured apps)|(files)|(leap brush)|(magic leap assist)|(model viewer)|(qr reader)|(settings)|(sktemplate_multi)|(spaces)|(spatial audio demo)|(web browser)|(wildfire)|(wivrn)
07-13 19:42:23.004  3773  3801 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_REPLACED dat=package:org.meumeu.wivrn flg=0x4000010 (has extras) } to com.android.musicfx/.Compatibility$Receiver
07-13 19:42:23.023  3773  3800 I ActivityTaskManager: Displayed org.meumeu.wivrn/android.app.NativeActivity: +1m25s943ms
07-13 19:42:23.207  3464  3693 I VoiceService: offline_intent_iface.cpp:389: [updateVarVecValues2SysGramStr]----- The values of VoiceConcept 1 (string App) updated to (ar brochure)|(custom fit)|(featured apps)|(files)|(leap brush)|(magic leap assist)|(model viewer)|(qr reader)|(settings)|(sktemplate_multi)|(spaces)|(spatial audio demo)|(web browser)|(wildfire)|(wivrn)
07-13 19:42:30.207  5448  5522 I AppListUpdateHandler: launching package [org.meumeu.wivrn]; class [android.app.NativeActivity]
07-13 19:42:30.207  3773  7260 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10210000 cmp=org.meumeu.wivrn/android.app.NativeActivity} from uid 10084
07-13 19:42:30.239  3773  3802 I ActivityManager: Start proc 7296:org.meumeu.wivrn/u0a67 for activity {org.meumeu.wivrn/android.app.NativeActivity}
07-13 19:42:30.276  3773  3794 I MagicLeapTaskController: onActivityEnterAnimationCompleteLocked: org.meumeu.wivrn/android.app.NativeActivity isAr=true renderProcessUid=10067
07-13 19:42:30.276  3969  3969 D StatusBar: package name = org.meumeu.wivrn
07-13 19:42:30.276  3969  3969 D StatusBar: package name = org.meumeu.wivrn
07-13 19:42:30.277  3969  3969 D StatusBar: package name = org.meumeu.wivrn
07-13 19:42:30.276  3773  3794 I MagicLeapTaskController: onActivityEnterAnimationCompleteLocked: org.meumeu.wivrn/android.app.NativeActivity isAr=true renderProcessUid=10067
07-13 19:42:30.501  7296  7321 E linker  : library "/system/lib64/libopenxr_layer_core_validation.so" ("/system/lib64/libopenxr_layer_core_validation.so") needed or dlopened by "/data/app/org.meumeu.wivrn-09rDM-Al64bXn1zf1payaw==/base.apk!/lib/x86_64/libopenxr_loader.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="/data/app/org.meumeu.wivrn-09rDM-Al64bXn1zf1payaw==/lib/x86_64:/data/app/org.meumeu.wivrn-09rDM-Al64bXn1zf1payaw==/base.apk!/lib/x86_64", permitted_paths="/data:/mnt/expand:/data/data/org.meumeu.wivrn"]
07-13 19:42:30.501  7296  7321 W OpenXR-Loader: Warning [GENERAL | xrCreateInstance | OpenXR-Loader] : ApiLayerInterface::LoadApiLayers skipping layer XR_APILAYER_LUNARG_core_validation, failed to load with message "dlopen failed: library "/system/lib64/libopenxr_layer_core_validation.so" needed or dlopened by "/data/app/org.meumeu.wivrn-09rDM-Al64bXn1zf1payaw==/base.apk!/lib/x86_64/libopenxr_loader.so" is not accessible for the namespace "classloader-namespace""
07-13 19:42:30.506  7296  7321 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x28 in tid 7321 (Thread-2), pid 7296 (rg.meumeu.wivrn)
07-13 19:42:30.536  7326  7326 F DEBUG   : pid: 7296, tid: 7321, name: Thread-2  >>> org.meumeu.wivrn <<<
07-13 19:42:30.538  7326  7326 F DEBUG   :       #00 pc 00000000000ebd45  /data/app/org.meumeu.wivrn-09rDM-Al64bXn1zf1payaw==/base.apk!libc++_shared.so (offset 0x5559000) (BuildId: 7921f33b2ac7042bb169ac8d0f6bebb24e397751)
07-13 19:42:30.538  7326  7326 F DEBUG   :       #01 pc 00000000000ebb47  /data/app/org.meumeu.wivrn-09rDM-Al64bXn1zf1payaw==/base.apk!libc++_shared.so (offset 0x5559000) (__gxx_personality_v0+135) (BuildId: 7921f33b2ac7042bb169ac8d0f6bebb24e397751)
07-13 19:42:30.538  7326  7326 F DEBUG   :       #02 pc 00000000003818e4  /data/app/org.meumeu.wivrn-09rDM-Al64bXn1zf1payaw==/base.apk (offset 0x5778000) (BuildId: 5eecc2200e9a198e3287762c02114023ebe37f97)
07-13 19:42:30.538  7326  7326 F DEBUG   :       #03 pc 000000000038197e  /data/app/org.meumeu.wivrn-09rDM-Al64bXn1zf1payaw==/base.apk (offset 0x5778000) (BuildId: 5eecc2200e9a198e3287762c02114023ebe37f97)
07-13 19:42:30.538  7326  7326 F DEBUG   :       #04 pc 00000000004914d4  /data/app/org.meumeu.wivrn-09rDM-Al64bXn1zf1payaw==/base.apk (offset 0x5778000) (BuildId: 5eecc2200e9a198e3287762c02114023ebe37f97)
07-13 19:42:30.538  7326  7326 F DEBUG   :       #05 pc 00000000003d7e6c  /data/app/org.meumeu.wivrn-09rDM-Al64bXn1zf1payaw==/base.apk (offset 0x5778000) (BuildId: 5eecc2200e9a198e3287762c02114023ebe37f97)
07-13 19:42:30.538  7326  7326 F DEBUG   :       #06 pc 00000000003db466  /data/app/org.meumeu.wivrn-09rDM-Al64bXn1zf1payaw==/base.apk (offset 0x5778000) (BuildId: 5eecc2200e9a198e3287762c02114023ebe37f97)
07-13 19:42:30.538  7326  7326 F DEBUG   :       #07 pc 000000000040dc71  /data/app/org.meumeu.wivrn-09rDM-Al64bXn1zf1payaw==/base.apk (offset 0x5778000) (BuildId: 5eecc2200e9a198e3287762c02114023ebe37f97)
07-13 19:42:30.538  7326  7326 F DEBUG   :       #08 pc 000000000040e0dc  /data/app/org.meumeu.wivrn-09rDM-Al64bXn1zf1payaw==/base.apk (offset 0x5778000) (android_main+124) (BuildId: 5eecc2200e9a198e3287762c02114023ebe37f97)
07-13 19:42:30.538  7326  7326 F DEBUG   :       #09 pc 00000000004ab038  /data/app/org.meumeu.wivrn-09rDM-Al64bXn1zf1payaw==/base.apk (offset 0x5778000) (BuildId: 5eecc2200e9a198e3287762c02114023ebe37f97)
07-13 19:42:30.930  3773  7330 W ActivityTaskManager:   Force finishing activity org.meumeu.wivrn/android.app.NativeActivity
07-13 19:42:30.946  3773  4156 I ActivityManager: Process org.meumeu.wivrn (pid 7296) has died: fore TOP 
07-13 19:42:31.431  3773  3794 W ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{c8c7544 u0 org.meumeu.wivrn/android.app.NativeActivity t-1 f}
07-13 19:42:46.504  5448  5522 I AppListUpdateHandler: launching package [org.meumeu.wivrn]; class [android.app.NativeActivity]
07-13 19:42:46.504  3773  4156 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10210000 cmp=org.meumeu.wivrn/android.app.NativeActivity} from uid 10084
07-13 19:42:46.545  3773  3802 I ActivityManager: Start proc 7397:org.meumeu.wivrn/u0a67 for activity {org.meumeu.wivrn/android.app.NativeActivity}
07-13 19:42:46.578  3773  3794 I MagicLeapTaskController: onActivityEnterAnimationCompleteLocked: org.meumeu.wivrn/android.app.NativeActivity isAr=true renderProcessUid=10067
07-13 19:42:46.578  3969  3969 D StatusBar: package name = org.meumeu.wivrn
07-13 19:42:46.578  3969  3969 D StatusBar: package name = org.meumeu.wivrn
07-13 19:42:46.579  3969  3969 D StatusBar: package name = org.meumeu.wivrn
07-13 19:42:46.578  3773  3794 I MagicLeapTaskController: onActivityEnterAnimationCompleteLocked: org.meumeu.wivrn/android.app.NativeActivity isAr=true renderProcessUid=10067
07-13 19:42:46.807  7397  7424 E linker  : library "/system/lib64/libopenxr_layer_core_validation.so" ("/system/lib64/libopenxr_layer_core_validation.so") needed or dlopened by "/data/app/org.meumeu.wivrn-09rDM-Al64bXn1zf1payaw==/base.apk!/lib/x86_64/libopenxr_loader.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="/data/app/org.meumeu.wivrn-09rDM-Al64bXn1zf1payaw==/lib/x86_64:/data/app/org.meumeu.wivrn-09rDM-Al64bXn1zf1payaw==/base.apk!/lib/x86_64", permitted_paths="/data:/mnt/expand:/data/data/org.meumeu.wivrn"]
07-13 19:42:46.807  7397  7424 W OpenXR-Loader: Warning [GENERAL | xrCreateInstance | OpenXR-Loader] : ApiLayerInterface::LoadApiLayers skipping layer XR_APILAYER_LUNARG_core_validation, failed to load with message "dlopen failed: library "/system/lib64/libopenxr_layer_core_validation.so" needed or dlopened by "/data/app/org.meumeu.wivrn-09rDM-Al64bXn1zf1payaw==/base.apk!/lib/x86_64/libopenxr_loader.so" is not accessible for the namespace "classloader-namespace""
07-13 19:42:46.812  7397  7424 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x28 in tid 7424 (Thread-2), pid 7397 (rg.meumeu.wivrn)
07-13 19:42:46.842  7430  7430 F DEBUG   : pid: 7397, tid: 7424, name: Thread-2  >>> org.meumeu.wivrn <<<
07-13 19:42:46.843  7430  7430 F DEBUG   :       #00 pc 00000000000ebd45  /data/app/org.meumeu.wivrn-09rDM-Al64bXn1zf1payaw==/base.apk!libc++_shared.so (offset 0x5559000) (BuildId: 7921f33b2ac7042bb169ac8d0f6bebb24e397751)
07-13 19:42:46.843  7430  7430 F DEBUG   :       #01 pc 00000000000ebb47  /data/app/org.meumeu.wivrn-09rDM-Al64bXn1zf1payaw==/base.apk!libc++_shared.so (offset 0x5559000) (__gxx_personality_v0+135) (BuildId: 7921f33b2ac7042bb169ac8d0f6bebb24e397751)
07-13 19:42:46.843  7430  7430 F DEBUG   :       #02 pc 00000000003818e4  /data/app/org.meumeu.wivrn-09rDM-Al64bXn1zf1payaw==/base.apk (offset 0x5778000) (BuildId: 5eecc2200e9a198e3287762c02114023ebe37f97)
07-13 19:42:46.843  7430  7430 F DEBUG   :       #03 pc 000000000038197e  /data/app/org.meumeu.wivrn-09rDM-Al64bXn1zf1payaw==/base.apk (offset 0x5778000) (BuildId: 5eecc2200e9a198e3287762c02114023ebe37f97)
07-13 19:42:46.843  7430  7430 F DEBUG   :       #04 pc 00000000004914d4  /data/app/org.meumeu.wivrn-09rDM-Al64bXn1zf1payaw==/base.apk (offset 0x5778000) (BuildId: 5eecc2200e9a198e3287762c02114023ebe37f97)
07-13 19:42:46.843  7430  7430 F DEBUG   :       #05 pc 00000000003d7e6c  /data/app/org.meumeu.wivrn-09rDM-Al64bXn1zf1payaw==/base.apk (offset 0x5778000) (BuildId: 5eecc2200e9a198e3287762c02114023ebe37f97)
07-13 19:42:46.843  7430  7430 F DEBUG   :       #06 pc 00000000003db466  /data/app/org.meumeu.wivrn-09rDM-Al64bXn1zf1payaw==/base.apk (offset 0x5778000) (BuildId: 5eecc2200e9a198e3287762c02114023ebe37f97)
07-13 19:42:46.843  7430  7430 F DEBUG   :       #07 pc 000000000040dc71  /data/app/org.meumeu.wivrn-09rDM-Al64bXn1zf1payaw==/base.apk (offset 0x5778000) (BuildId: 5eecc2200e9a198e3287762c02114023ebe37f97)
07-13 19:42:46.843  7430  7430 F DEBUG   :       #08 pc 000000000040e0dc  /data/app/org.meumeu.wivrn-09rDM-Al64bXn1zf1payaw==/base.apk (offset 0x5778000) (android_main+124) (BuildId: 5eecc2200e9a198e3287762c02114023ebe37f97)
07-13 19:42:46.843  7430  7430 F DEBUG   :       #09 pc 00000000004ab038  /data/app/org.meumeu.wivrn-09rDM-Al64bXn1zf1payaw==/base.apk (offset 0x5778000) (BuildId: 5eecc2200e9a198e3287762c02114023ebe37f97)
07-13 19:42:47.175  3773  7433 W ActivityTaskManager:   Force finishing activity org.meumeu.wivrn/android.app.NativeActivity
07-13 19:42:47.192  3773  4156 I ActivityManager: Process org.meumeu.wivrn (pid 7397) has died: fore TOP 
07-13 19:42:47.676  3773  3794 W ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{e78c72 u0 org.meumeu.wivrn/android.app.NativeActivity t-1 f}
```

sooooooo fun :/

**Comment by technobaboo** [comment]
any ideas? i think i'm doing it wrong

**Pull request merged**
