### PR TITLE
Set Default CMAKE_INSTALL_LIBDIR

### PR DESCRIPTION
**Pull request by damaestro**
- Set the default based on user provided location or ours

### CODE REVIEW

**Comment by damaestro** [comment]
Hmm, well this seems to work like I'd expect, but there might be a SONAME filename path issue:

```
   /usr/lib64/wivrn/runtime/libmonado.so
   /usr/lib64/wivrn/runtime/libmonado.so.0.17
   /usr/lib64/wivrn/runtime/libmonado.so.24
```
```
<mock-chroot> sh-5.2# ls -al
total 920
drwxr-xr-x. 1 mockbuild mock    124 Aug  3 16:09 .
drwxr-xr-x. 1 mockbuild mock     14 Aug  3 16:09 ..
lrwxrwxrwx. 1 mockbuild mock     15 Aug  3 16:09 libmonado.so -> libmonado.so.24
-rwxr-xr-x. 1 mockbuild mock 152072 Aug  3 16:09 libmonado.so.0.17
lrwxrwxrwx. 1 mockbuild mock     17 Aug  3 16:09 libmonado.so.24 -> libmonado.so.0.17
-rwxr-xr-x. 1 mockbuild mock 777576 Aug  3 16:09 libopenxr_wivrn.so
```
```
<mock-chroot> sh-5.2# find . -type f -exec readelf -d {} \;|grep SONAME
 0x000000000000000e (SONAME)             Library soname: [libmonado.so.24]
```

The `libopenxr_wivrn.so` is correctly an unversioned DSO (a Vulkan ICD).
The actual file `libmonado.so.0.17` is correctly a versioned SONAME matching the upstream versioning `libmonado.so.24`.

So there is something odd with the filesystem layout. I would have expected:

```
<mock-chroot> sh-5.2# ls -al
total 920
drwxr-xr-x. 1 mockbuild mock    124 Aug  3 16:09 .
drwxr-xr-x. 1 mockbuild mock     14 Aug  3 16:09 ..
lrwxrwxrwx. 1 mockbuild mock     15 Aug  3 16:09 libmonado.so -> libmonado.so.24
-rwxr-xr-x. 1 mockbuild mock 152072 Aug  3 16:09 libmonado.so.24
-rwxr-xr-x. 1 mockbuild mock 777576 Aug  3 16:09 libopenxr_wivrn.so
```

**Comment by damaestro** [comment]
What is the purpose of shipping the `libmonado.so`? I know it's been discussed but I forget the use-case.

**Comment by damaestro** [comment]
https://gitlab.freedesktop.org/monado/monado/-/merge_requests/2285/ doesn't seem to be causing this.

**Comment by damaestro** [comment]
When I set `-DCMAKE_PROJECT_VERSION=%{version}` (and version is the WiVRn version) I see the actual file named `libmonado.so.0.17`. When I don't set this, the actual file ends up being named `libmonado.so.0.0.0`.

**Comment by damaestro** [comment]
When building with the following set things look good:

```
  -DCMAKE_PROJECT_VERSION=%{monado_version} \
  -DGIT_DESC=v%{version} \
```

`%{version}` is the WiVRn tag. (i.e. `0.17`)
`%{monado_version}` is the upstream tag. (i.e. `24.0.0`)

```
<mock-chroot> sh-5.2# ls -al
total 924
drwxr-xr-x. 1 mockbuild mock    128 Aug  3 17:22 .
drwxr-xr-x. 1 mockbuild mock     14 Aug  3 17:22 ..
lrwxrwxrwx. 1 mockbuild mock     15 Aug  3 17:22 libmonado.so -> libmonado.so.24
lrwxrwxrwx. 1 mockbuild mock     19 Aug  3 17:22 libmonado.so.24 -> libmonado.so.24.0.0
-rwxr-xr-x. 1 mockbuild mock 152072 Aug  3 17:22 libmonado.so.24.0.0
-rwxr-xr-x. 1 mockbuild mock 781664 Aug  3 17:22 libopenxr_wivrn.so
```

So from my side things look good.

**Comment by xytovl** [comment]
> What is the purpose of shipping the `libmonado.so`? I know it's been discussed but I forget the use-case.

libmonado exposes some functions not available through OpenXR such as moving spaces. It will be the mechanism to provide battery status and probably add external trackers.

**Comment by xytovl** [comment]
This pull request only changes the mechanism to set library path, and the odd sonames are unrelated, right?

For sonames, I'll have to find a mechanism to remove it from libmonado, as it should now only be loaded through dlopen.

**Comment by damaestro** [comment]
> From a clean build dir:
> 
> ```
> cmake .. -GNinja -DCMAKE_INSTALL_PREFIX=/tmp/wivrn -DCMAKE_BUILD-TYPE=Release
[...]
> ```
> CMAKE_INSTALL_LIBDIR:PATH=lib64
> ```

Yeah, that makes sense. I'm specifying `CMAKE_INSTALL_LIBDIR` and this PR allows that to be user-overridden and otherwise use what is configured in the code.

However, after thinking about having libmonado available I'm likely going to need to deal with that or make WiVRn conflict with the Monado package since the SONAME is going to be in the same. I will deal with that in a different way and this PR should still be valid.

**Comment by damaestro** [comment]
@xytovl ah, I see now. Okay, give me a bit to think through a different proposal that might also help us with conflicting with a system Monado install (i.e. `libmonado.so` collision)

**Comment by damaestro** [comment]
Closing this in favor of a different approach now that I need to think about keeping monado not visible to the linker.

**Pull request closed without merging**
